/* DO NOT EDIT.
 * Generated by ..\..\bin\Debug\vtkEncodeString-8.1.exe
 * 
 * Declare the vtkDepthOfFieldPassFS string.
 *
 */
#ifndef __vtkDepthOfFieldPassFS_h
#define __vtkDepthOfFieldPassFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkDepthOfFieldPassFS;

#endif /* #ifndef __vtkDepthOfFieldPassFS_h */
